### ISSUE TITLE
very high CPU usage

### ISSUE THREAD

**Issue by Place1** [lmartinking/webscreensaver#10]
I'm using webscreensaver with https://github.com/archagy/webnuxsaver to display videos. webnuxsaver is essentially just an html page with a <video> on it.

I'm using a 149MB .mp4 video (i'm not sure if size has anything to do with it). and it's consuming my entire CPU to the point of making my laptop almost unresponsive.

any ideas?

edit: also, this crashes xscreensaver when I try and preview.

**Comment by lmartinking** [comment]
Hi @Place1 `webscreensaver` uses the webkit that is integrated with GTK. I don't think it's as performant as Chrome for example, and I think I doesn't use V8 either (rather `JavaScriptCore`).

Perhaps you could try the page in Midori or "GNOME Web"?

**Comment by lmartinking** [comment]
(Closing due to the issue being 2 years old, let me know how the updated version goes @Place1 !)
