### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by lmartinking** [lmartinking/webscreensaver#12]
@tom-mi I haven't formally defined a licence for this project. I got an email from someone who wanted to make a debian package however they need an official licence. I want to run this past you since you've made nontrivial contributions.

Would you be OK with GPLv2 or 3?

**Comment by tom-mi** [comment]
@lmartinking Yes, that's fine.

**Comment by lmartinking** [comment]
Fixed in `05a736c00fb66d902269d492d1a07febb7c4ed95`
