### ISSUE TITLE
Please update instructions to advise which packages to install in Ubuntu

### ISSUE THREAD

**Issue by philCryoport** [lmartinking/webscreensaver#16]
Suggestions for those wanting to install in Ubuntu based upon my semi-n00b experience:

* Ubuntu 16.04.4 LTS uses xscreensaver 5.34 which is a few years old; good luck on building the newer version.  Instead I suggest installing xUbuntu 17.10.1 which comes with xscreensaver 5.36 (not the latest version, but close enough to work) 
* In addition, Ubuntu Desktop 17.10.1 comes with Wayland / gdm -- which throws errors with xscreensaver when it comes to advanced-compositing or screen-locking.  Instead, I suggest installing Lubuntu 17.10.1 which comes with lxde which *does* play nicely with xscreensaver.
* Here are the things one must install to get webscreensaver to work in Lubuntu 17.10.1:
`$ sudo apt update && sudo apt install -y python2.7 python-gi libwebkitgtk-3.0.0 gir1.2-webkit-3.0 at-spi2-core`
`$ xscreensaver`
(click Settings, wait for the list of and then close out of xscreensaver -- this will make sure you have a complete `~/.xscreensaver` file)
* Here's an easy way to see if it's working via the command-line:
`$ /usr/lib/webscreensaver -url https://www.google.com/`

**Comment by devzer01** [comment]
thanks a bunch

**Comment by lmartinking** [comment]
Hi @philCryoport, trthanks for the kind suggestion. I have updated the instructions to be relevant to Ubuntu 19.04 in `README.md`. :-)
