### ISSUE TITLE
React-core.min.js throwing an error

### ISSUE THREAD

**Issue by philCryoport** [lmartinking/webscreensaver#17]
`/usr/lib/webscreensaver -url https://p.datadoghq.com/sb/<public URL>?tv_mode=true`

result:
Console reports:
`** Message: console message: https://p.datadoghq.com/static/v/34.261313/js/react-core.min.js @16: uncaught`

And the display is just plain _ooooogly_

**Comment by lmartinking** [comment]
Hey @philCryoport do you have a (public) URL I could try ?

This could very well be related to an old webkit version as mentioned in other tickets.

**Comment by philCryoport** [comment]
I can't reveal the public URL, sorry

...and I've switched to using [xtrlock](http://manpages.ubuntu.com/manpages/trusty/man1/xtrlock.1x.html) so this issue is moot

Datadog does offer a free-up-to-5-hosts plan in their infrastructure product so you could get a login and test against it...
