### ISSUE TITLE
Could we get a redo on this to use something besides the deprecated and unstable webkit?

### ISSUE THREAD

**Issue by Blueshawk** [lmartinking/webscreensaver#18]
I haven't gotten web video to run in about a year and recently switched to 18.04 xubuntu only to find that midori is no longer in repo. I haven't been able to solve dependencies to get back to where I was. I really liked being able to get a web page and had actually hacked a bunch of url's into the code. Breaking the url list out to a config file would be terrific too, as would a swtich to allow sequential display of sites. 
I had video from the ISS hdev experiment and several websites and webcams running randomly while I worked and really miss them. I've fiddled a bit but I'm not very good with this style of code.
(or any really/getting better with arduino and a bit of c)

@lmartinking please heeaalp!

**Comment by lmartinking** [comment]
Hey @Blueshawk I don't run ubuntu as my daily driver, but it might be as simple as changing the calls to `gi.require_version`.... Would you mind giving it a try for me? 😄

**Comment by lmartinking** [comment]
Hi @Blueshawk, I've finally got around to updating to WebKit2, as I'm back to Ubuntu as my daily driver. :-)

**Comment by Blueshawk** [comment]
That's good. Wish I could have been more help on this. There have been a few developments along other branches you might find interesting, cookies and such. I still use this for weather but never really got video working again. I still think LIVE ISS cam was the greatest screensaver ever. :P 
Also, the CIRA weather satellite works pretty well. 
This is the url I'm using with it in case you're interested. Warning, bigtime bandwidth usage.

`https://rammb-slider.cira.colostate.edu/?sat=goes-16&z=2&im=30&ts=2&st=0&et=0&speed=200&motion=loop&map=1&lat=0&opacity%5B0%5D=1&opacity%5B1%5D=0.7&opacity%5B2%5D=1&hidden%5B0%5D=0&hidden%5B1%5D=0&hidden%5B2%5D=0&pause=0&slider=-1&hide_controls=0&mouse_draw=0&follow_feature=0&follow_hide=0&s=rammb-slider&sec=conus&p%5B0%5D=geocolor&p%5B1%5D=mrms_reflectivity_at_lowest_altitude&p%5B2%5D=cira_glm_l2_group_energy&x=5709&y=3839`

Needless to say, that tests a string buffer pretty well, its a book! :P All those are url parameters, very useful for setting it just how you like it including layers etc. 
Cheers,
Ray

**Comment by Blueshawk** [comment]
Got a chance and updated, editing in my URL list and whatya know! ISS works now, w00t!
