### ISSUE TITLE
Determine if screensaver is active or not

### ISSUE THREAD

**Issue by chsymann** [lmartinking/webscreensaver#19]
Thanks a lot for sharing this nice little feature. It works very well for us. 
But I realized, that the process keeps running, even when the screensaver is not active. 
For us that is a problem, because the screensaver-webpage fetches news by using a JavaScript interval and they should only be pulled when the screensaver is running.
I already tried a JavaScript check like `document.hidden` without success.
Does someone has any idea on how to check if the screensaver is really visible?
Thanks a lot!

**Comment by lmartinking** [comment]
Hi @chsymann89 are you still having this issue? What distro and xscreensaver version ?

**Comment by peter-vanpoucke** [comment]
I don't see the same behaviour like you do (process being still there when there's no screensaver). Maybe some scripting that got stuck (wild guess).
You could use `xscreensaver-command -time` or `xscreensaver-command -watch`, but then you'd need some batch script to trigger/monitor those.

**Comment by lmartinking** [comment]
Going to close because of age
