### ISSUE TITLE
Ideas for further development.

### ISSUE THREAD

**Issue by Blueshawk** [lmartinking/webscreensaver#20]
I think a url "hack" config file would be a nice addition. something like -config-file: and then urls set up in the same parsing as in the random hacks routine. I keep forgetting to bash on this so I figured I'd drop it as an idea. 

I also think a switch for xscreensaver(no idea how this works) to make it read the url list sequentially instead of the current random would be useful. As above. Time and brainpower not in abundance right now. I blame astronomy.

**Comment by lmartinking** [comment]
Hi @Blueshawk you might be interested in the PR which is currently up for sites list.
