### ISSUE TITLE
webscreensaver not working with Ubuntu 19.10

### ISSUE THREAD

**Issue by rimatheou** [lmartinking/webscreensaver#22]
System Environment:

Ubuntu 19.10 Eoan Ermine
5.3.0-19-generic
Unity
XScreenSaver 5.42

I can choose webscreensaver from the drop down menu list in xscreensaver-demo and the screen is getting black after 1 minute, but it doesn't appear any url, neither a random one nor a specific.
[xscreensaver.txt](https://github.com/lmartinking/webscreensaver/files/3835932/xscreensaver.txt)
Any ideas?

**Comment by thomas-gt** [comment]
Same problem. Tested on 2 different PC with Ubuntu 19.10.
Works fine on 18.04.

**Comment by lmartinking** [comment]
Hi @rimatheou @thomas-gt , I've recently updated to 19.10 here. I'm using xfce+screensaver and it's working (the famous "it works on my machine").
 
Are you able to run `./webscreensaver` ? What desktop environment are you using? Are you using Xorg or Wayland? Could you capture some logs / stderr output and post here... :-)

**Comment by thomas-gt** [comment]
Hi @lmartinking 

I'm running 19.10 with Gnome/Xorg.

`/usr/lib/xscreensaver/webscreensaver` appears to work when ran directly (random stuff displayed it seems).
When launching `xscreensaver` manually (ie not in background) and testing `webscreensaver` inside I get a message :

```
...webscreensaver:54 PyGTKDeprecationWarning Using positional arguments 
with the GObjects contructor has been deprecated...
self.win = Gtk.Window(Gtk.WindowType.POPUP)
...
```
Sorry for uncomplete message, pretty hard to screenshot :smiley: 

In the code it seems be related to :
```
	def setup_window(self):
		'''Perform some magic (if needed) to set up a Gtk window'''
		if self.window_id:
			self.win = Gtk.Window(Gtk.WindowType.POPUP)

			gdk_display = GdkX11.X11Display.get_default()
			self.gdk_win = GdkX11.X11Window.foreign_new_for_display(gdk_display, 
self.window_id)
```
But I cannot be sure this is real cause though.
Thanks.

**Comment by jackmawer** [comment]
Same problem here, it appears. Running the app on its own works fine, but xscreensaver gives a blank screen

**Comment by jackmawer** [comment]
Aside from the depreciation, it looks like having a GTK WindowType of Popup is related to the issue. Using a normal or "TOPLEVEL" window appears normally (although neither successfully attach to the window belonging to the provided id or xscreensaver) but a popup type makes the window seemingly not appear.

**Comment by jackmawer** [comment]
Commenting out line 62, the reparenting line, seems to work around this issue, so there's probably an issue with reparenting to the given window id.

**Comment by lmartinking** [comment]
I'm afraid I'm not in a position to test with Gnome at the moment.

I can try and explain the reasons (from what I remember when I wrote the code).

XScreensaver will create a XWindow, which is expects all screen savers/hacks to draw on. It sets an XAtom on the "root window", but also passes the XWINID to the subprocess via environment variable. This WINID is also passed through when using the xscreensaver control panel (for the screensaver previews).

We have to use that window as the basis for our toplevel window, hence the use of [`foreign_new_for_display`](https://lazka.github.io/pgi-docs/GdkX11-3.0/classes/X11Window.html#GdkX11.X11Window.foreign_new_for_display).

I think I used the `POPUP` type so as to avoid having window decorations...

**Comment by mindcombatant** [comment]
this seems to still be a problem on Ubuntu 20.04 and compiled-from-source XScreenSaver 6.0. i can't figure out the problem, but it seems to be the same symptoms, and commenting out the reparenting line (63 now) still sorta works around it.

**Comment by lmartinking** [comment]
@mindcombatant  @jackmawer Are you both running wayland, or just xorg?

**Comment by mindcombatant** [comment]
just xorg, on the proprietary nvidia driver, all other parts of xscreensaver work perfectly, including other hacks.

**Comment by mindcombatant** [comment]
so, an update:
as i have xscreensaver set to start up and lock immediately after login, on my last reboot and login, this screensaver seemed to successfully run. i think this was due to another issue i've been having where Gnome fails to start properly the first time i log in, as when i got out of xscreensaver gnome was telling me to log out and log back in again. regardless of the reasons, this leads me to believe that the incompatability is with Gnome, it must do something differently with XWindows or something, as when i'd logged in properly and tried to launch xscreensaver with only this screensaver selected in config, webscreensaver would not run again.

**Comment by lmartinking** [comment]
It could be an issue due to compositing as well. 🤷 

I'm going to close this issue since it's been years!
