### ISSUE TITLE
Conflicts with the login screen

### ISSUE THREAD

**Issue by beucismis** [lmartinking/webscreensaver#24]
Hi, xscreensaver locks the session after 1 minute. When I wanted to open it later, there was a strange situation...

![photo_2020-05-14_18-00-32](https://user-images.githubusercontent.com/40023234/81950611-d37a4100-960c-11ea-894c-f48ade2a2c32.jpg)

**Comment by adlgrbz** [comment]
**?**

**Comment by lmartinking** [comment]
Hi @beucismis thanks for contacting me, what's the issue exactly? Are you expecting the screensaver to stop when the unlocker window appears?

**Comment by beucismis** [comment]
> Are you expecting the screensaver to stop when the unlocker window appears?
Yep.

**Comment by mindcombatant** [comment]
modern versions of xscreensave (i think 6.0 onward) do not have the behavior of stopping the screensaver when the login prompt comes up anymore anyway, so i'm all for marking this as a non-issue, honestly.
