### ISSUE TITLE
Issue with cookies acceptation

### ISSUE THREAD

**Issue by nettlebay** [lmartinking/webscreensaver#27]
Hello! Webscreensaver works fine on my Linux Manjaro except many pages are not usable due to the cookie acceptance request. Here in the manager but it's the same as the screensaver start.
Screenshot: https://i.imgur.com/GfBK1NB.png

**Comment by lmartinking** [comment]
Hi @nettlebay , you might need to try `-cookie-file PATH` which enables persistent storage of cookies.
