### ISSUE TITLE
Webscreensaver no content on blank screen CentOS Stream 8

### ISSUE THREAD

**Issue by nurbecause** [lmartinking/webscreensaver#28]
Hello,

I'm trying to built a kiosk client with a screensaver which shows a website. The screensaver would show basic information and the normal browser shows an interactive menue. I installed webscreensaver to /usr/bin/ so I can launch it via xscreensaver.
When I am entering a low timeout, so i can watch, that the xscreensaver should do something, it shows only a black (blank) screen and not the infopage.
If I wait for timeout I can see cal with ps auxl: kiosk       5815 11.7  7.8 86250048 88068 tty2   SNl+ 17:32   0:00 python3 /usr/bin/webscreensaver -url https://liveuamap.com/de

But the screen is still empty (blank/black). 

Do you have an idea for this problem?

Regards,
nurbecause

**Comment by lmartinking** [comment]
Hi @nurbecause I'd love to help a bit here... What desktop environment is running? Are you able to run other XScreensaver modules?

**Comment by lmartinking** [comment]
@nurbecause I see the default for Centos 8 is Gnome 3. Did you follow similar instructions to: https://vitux.com/how-to-replace-gnome-screensaver-with-xscreensaver-on-ubuntu/

**Comment by nurbecause** [comment]
@lmartinking Thanks for helping me.
I installed the packages xscreensaver, cloned the webscreensaver python script to `/usr/bin/`, so I can open Websites from console with `webscreensaver -url http://google.de`.
But the xscreensaver is showing me a blank screen if i run `xscreensaver &` on a terminal

**Comment by nurbecause** [comment]
@lmartinking How are we going to proceed here? Are you running some tests?

**Comment by KFDCompiled** [comment]
@nurbecause did you get this figured out?

**Comment by strangmann** [comment]
It seems I have the same problem on CentOS 9. I already created a issue #31 
@nurbecause Have you solved this problem?

**Comment by lmartinking** [comment]
@strangmann what desktop environment are you using? I've just verified that Gnome seems to break displaying of the embedded view -- both in the xscreensaver-demo window and fullscreen.

**Comment by lmartinking** [comment]
@nurbecause unfortunately it's a gnome issue -- I have verified that XFCE4 works on Ubuntu 22.04 LTS (no wayland).
