### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by robrockit** [lmartinking/webscreensaver#29]
I have webscreensaver installed along with xscreensaver. I am running Debian 11(bullseye). Seeing the following deprecation warnings:

- /usr/libexec/xscreensaver/websccreensaver:55: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "type" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations self.win = Gtk.Window(Gtk.WindowType.POPUP)
- /usr/libexec/xscreensaver/websccreensaver:90 DeprecationWarning: WebKit2.Settings.set_enable_accelerated_2d_canvas is deprecated settings.set_enable_accelerated_2d_canvas(True)

I don't know Python well enough to go poking through the code to try and fix this. Any help would be greatly appreciated. Thanks!

**Comment by kristiansong** [comment]
I had tried followings, now no warning, but did not work(but it works when I run  _python webscreensaver__ in command line).
1) add keyword type: self.win = Gtk.Window(type=Gtk.WindowType.POPUP)
2) comment codes about settings.set_enable_accelerated_2d_canvas:
#try:
#           settings.set_enable_accelerated_2d_canvas(True)
#        except Exception as err:
#            print("Could not enable Accelerated 2D Canvas: {}".format(err))

**Comment by lmartinking** [comment]
@kristiansong thanks for the report, I have fixed these now :-D
