### ISSUE TITLE
BadDrawable (invalid Pixmap or Window parameter)

### ISSUE THREAD

**Issue by harayz** [lmartinking/webscreensaver#3]
i was not able to get it run properly and below was the error received. please help, thanks~

*\* (webscreensaver:13487): WARNING **: The program 'webscreensaver' received an X Window System error.
This probably reflects a bug in the Adobe Flash plugin.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 370 error_code 9 request_code 139 minor_code 4)

**Comment by lmartinking** [comment]
Hi @harayz are you still having this issue with the GTK-3 version of `webscreensaver` (latest `master`) ??

**Comment by harayz** [comment]
just in time! i had just reinstalled my linux machine and will follow up after trying it again on a freshly installed distro.

**Comment by lmartinking** [comment]
Hi @harayz, any follow up on this?

**Comment by lmartinking** [comment]
(Closing due to age)
