### ISSUE TITLE
Can't edit .xscreensaver file. Not showing up in menu

### ISSUE THREAD

**Issue by LostOnTheLine** [lmartinking/webscreensaver#30]
I have been trying to get this to work & I can't figure out why it's not working. I am running a laptop with Proxmox, I installed `XFCE4`, Installed `sudo apt install python3 python3-gi gir1.2-webkit2-4.0 gir1.2-gtk-3.0`, Copy `webscreensaver` into `/usr/lib/xscreensaver`, Copy `webscreensaver.desktop` into `/usr/share/applications/screensavers` it wasn't working so I also copied `webscreensaver` into `/usr/libexec/xscreensaver` since that's where all of the screensavers seem to be, edited the `webscreensaver.desktop` to point to it, but it never shows up in the screensavers list.

I noticed that when I edit `~/.xscreensaver` (for me residing in `/home/USERNAME/.xscreensaver`) any edits I make to it are gone once the screensaver daemon is refreshed or just some time passes. It's not that I can't edit it. It edits just fine & if I close it & reopen it right after my changes are there, but they don't stick. What am I doing wrong?

**Comment by lmartinking** [comment]
Hi @LostOnTheLine did you kill/close the `xscreensaver` daemon before editing/saving `~/.xscreensaver`?

I'm not sure why its not showing up in the screensaver list in XFCE. Are the other `.desktop` items from `/usr/share/applications/screensavers` showing up? Are there any notable differences between a working on and the one from the repo (which you've edited)?

**Comment by LostOnTheLine** [comment]
So I got it working. Even with the daemon killed editing it went back when it loaded. I had to SSH in while the user was logged out, edit it with the user logged out & then login. Now it works. Thanks for the response
