### ISSUE TITLE
msft windows?

### ISSUE THREAD

**Issue by Jan02** [lmartinking/webscreensaver#4]
is there a way to make this work for msft windows?

**Comment by lmartinking** [comment]
Not easily. Screensavers are very operating system specific (even though they are just programs).

At the moment `webscreensaver` works only with `XScreensaver` on X11 based systems...

You might be able to port it to windows, but you'd have to do a lot of work with getting the dependencies working as well as package it into an `.exe` (then rename to `.scr`)... I also recall there is some Windows specific functions you need to call as well (which could be accomplished with `pywin32` perhaps).
