### ISSUE TITLE
Rendering issue when using Raspberry OS 64-bit (aarch64)

### ISSUE THREAD

**Issue by zakhildev** [lmartinking/webscreensaver#42]
Web browser is not rendering correctly on Raspberry OS systems. Chromium browser is working just fine.

* `uname -a`: `Linux $HOSTNAME 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux`
* `.xscreensaver`: [.xscreensaver](https://github.com/lmartinking/webscreensaver/files/14711832/xscreensaver.txt)

If you would need any other logs, etc. please let me know :)

Error preview (my custom site):
![screenshot](https://github.com/lmartinking/webscreensaver/assets/57961635/51b9c70d-4f33-4daa-bb11-a10a76198698)

Error preview (google.com):
![screenshot (1)](https://github.com/lmartinking/webscreensaver/assets/57961635/7e4c9784-a3d9-4658-b72e-ccb3fec673b4)

**Comment by smos** [comment]
Confirmed after applying OS updates. Was working previously on bookworm from I think January.

Same thing with a Hyperpixel 4 display.

**Comment by lmartinking** [comment]
@smos @zakhildev are you using Wayland? And does the issue occur even when running it as a window?

**Comment by smos** [comment]
No, not using Wayland. I use the Rpi base os image, add the minimum requirements for lxde so I can run chromium in kiosk mode.

I use this as the screensaver in my project https://GitHub.com/smos/nomad-hotspot/
I updated webscreensaver to the last from the repo, but that didn’t fix it. 

I also noted, when running from the CLI that run_javascript() is deprecated. I have not investigated into replacing this with evaluate_javascript() as it does not appear to take the same syntax.

**Comment by lmartinking** [comment]
@smos what happens if you run `./webscreensaver` (directly, not via XScreensaver)? Do you get the same image corruption?

**Comment by lmartinking** [comment]
@zakhildev chromium browser uses a different rendering engine (forked from WebKit long ago) so unfortunately we can't really compare the two.

Please try the suggestion in my comment above, thanks!

**Comment by smos** [comment]
```
webscreensaver -url http://172.17.88.1:8000
Cache directory: /home/kiosk/.cache/webscreensaver
Load changed: <WebKit2.WebView object at 0x7fb9058840 (WebKitWebView at 0x3847fb00)> <enum WEBKIT_LOAD_STARTED of type WebKit2.LoadEvent>
Load changed: <WebKit2.WebView object at 0x7fb9058840 (WebKitWebView at 0x3847fb00)> <enum WEBKIT_LOAD_COMMITTED of type WebKit2.LoadEvent>
Load changed: <WebKit2.WebView object at 0x7fb9058840 (WebKitWebView at 0x3847fb00)> <enum WEBKIT_LOAD_FINISHED of type WebKit2.LoadEvent>
```

yes, same corruption in windowed mode when ran directly.

Assume these are shell variables, made no difference setting them.

**Comment by lmartinking** [comment]
@smos could you do me a favour and try running this from source: https://github.com/jamiemcg/Remarkable

It also uses GtkWebKit2 so I want to eliminate that as the issue.

**Comment by lmartinking** [comment]
@smos any chance you could test the other branch? 🙏

**Comment by smos** [comment]
Good news, i just updated the RPi and it pulled down newer webkit gtk2 packages. A quick test reveals that this is fixed upstream in the library.Thank you for your time.Op 22 mei 2024 23:46 schreef Lucas Martin-King ***@***.***>:
@smos any chance you could test the other branch? 🙏
