### ISSUE TITLE
A tiny problem...

### ISSUE THREAD

**Issue by iyuvalk** [lmartinking/webscreensaver#5]
I tried installing this screensaver on my Ubuntu 15.10 and if I leave my computer idle I get a black screen with a few lines of yellow text. Is there something I'm not doing correctly? I copied the file, edited the programs section and selected webscreensaver as my screensaver in xscreensaver...

**Comment by lmartinking** [comment]
That usually happens when the program can't be started by `xscreensaver`.

Can you try running it manually and seeing if it displays anything?

**Comment by iyuvalk** [comment]
Hi,

It seems that it was a problem with my Ubuntu installation... At the
beginning I installed the default Ubuntu installation (with Unity and
lightdm) and than tried to install Gnome desktop and it wasn't, as it
turned out, a very good idea. I installed Gnome Ubuntu from scratch (and
re-installed all my apps again, of course) and now it seems that
xscreensaver works flawlessly - amazing...

Thanks a lot for all your help,
Yuval.

**Comment by lmartinking** [comment]
Glad to help you rubber duck! ;-)
