### ISSUE TITLE
WebGL never enabled?

### ISSUE THREAD

**Issue by akaihola** [lmartinking/webscreensaver#8]
In the `WebScreensaver` class, you have:

```
    def setup_browser(self):
        '''Sets up WebKit in our window'''
        self.browser = WebKit.WebView()

        # Try to enable webgl
        try:
            settings = browser.get_settings()
            settings.set_property('enable-webgl', True)
        except:
            pass
```

On the fourth last line, `settings = browser.get_settings()` refers to the identifier `browser` which is never imported or defined. As a result, you always get an exception which is silently caught. This should probably be `settings = self.browser.get_settings()` instead.

**Comment by lmartinking** [comment]
Hi @akaihola , thanks for the report!

I believe I've fixed it now on `master`. Care to give it a try?

**Comment by akaihola** [comment]
Well, I didn't actually try to enable WebGL, I just happened to notice this looking at the source code. It now looks correct to me.

Although unless you expect `self.browser.get_settings()` to fail in normal operation, you should probably move that before the `try:` block.

Also, using `logging` instead of print statements would enable you to easily print out the exception, too:

    logging.exception('Could not enable WebGL')

**Comment by lmartinking** [comment]
Hi @akaihola, I recall if a setting didn't exist, or could not be set, then an exception was thrown.

I'm not against using `logging` per se, but as a single script rather than a full on application, `print` is simpler.

**Comment by lmartinking** [comment]
(Closing due to issue being 3 years old)
