### ISSUE TITLE
Missing from xscreensaver

### ISSUE THREAD

**Issue by timrabbetts** [lmartinking/webscreensaver#9]
Hi,

This is awesome if I can get it to work.  I have moved webscreensaver into /usr/lib/xscreensaver but i cant see it as an option in the xscreensaver popup, which is what i need to do right?  I need to select it and also edit the ~/.xscreensaver file (which doesnt exist).  I am on ubuntu mate 16.  Please help this would be amazing to geet working!

Thanks Tim

**Comment by timrabbetts** [comment]
I have got further, the problem was I had the old mate screen saver default.  So now I have xscreensaver, and I have the .xscreensaver file and I have updated it to this:

  GL:                           romanboy -root                              \n\
                                tessellimage -root                          \n\
  GL:                           winduprobot -root                           \n\
  GL:                           splitflap -root                             \n\
                                testx11 -root                               \n\
                                webscreensaver                              \n\
-                               url www.google.com                          \n\


When I preview I see threejs horses fly planes which i assume is a bunch of random urls.  So I just need it to load the url and its working, any ideas?  I edited the file, but then xscreensaver added /n/ etc?

**Comment by timrabbetts** [comment]
Fixed it and its working thanks!!!
all needs to be on one line webscreensaver -url http://www.google.com /n/

**Comment by lmartinking** [comment]
Glad you rubber ducked this yourself :-)

I will clarify this in the reader.

**Comment by timrabbetts** [comment]
Ye, I was giving up a bit easy, but defo adding to the readme for others would help.
